# CI pipeline for Python automated tests

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '3.x'
  displayName: 'Install Python'

- script: |
    python -m pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    python -m pytest test.py
  displayName: 'Run automated tests'

- task: AzureWebApp@1
  displayName: 'Deploy to Azure App Service'
  inputs:
    azureSubscription: 'sc-cd-ci-cd-learning'
    appType: 'webAppLinux'
    appName: 'ahalder-cicd-learning'
    package: '$(System.DefaultWorkingDirectory)'
